### ISSUE TITLE
contact nav is missing in certification page

### ISSUE THREAD

**Issue by rakibhhridoy** [rakibhhridoy/rakibhhridoy.github.io#7]

**Comment by jungsominh** [comment]
can you provide a picture of details.

**Comment by rakibhhridoy** [comment]
[In drive](https://drive.google.com/drive/folders/15cOWFK8QWcDrI4rVoQExUaeC468_XN2e?usp=sharing)

**Comment by jungsominh** [comment]
assign me in this task
